### ISSUE TITLE
Test error line 4

### ISSUE THREAD

**Issue by cipo80** [SplitCriteria/dlm-helper#2]
Hi, I'm trying to create a .dlm to use my favorite torrent site, during test I received this error:

`root@srv:~/dlm# php DLMTester.php -s "halt" ./INFO
PHP Parse error:  syntax error, unexpected '' {' (T_CONSTANT_ENCAPSED_STRING), expecting '{' in /root/dlm/search.php on line 4
root@srv:~/dlm# php DLMTester.php -s "halt" ./INFO
PHP Parse error:  syntax error, unexpected '' {' (T_CONSTANT_ENCAPSED_STRING), expecting '{' in /root/dlm/search.php on line 4
root@srv:~/dlm# php DLMTester.php -s "halt" ./INFO
PHP Parse error:  syntax error, unexpected '' {' (T_CONSTANT_ENCAPSED_STRING), expecting '{' in /root/dlm/search.php on line 4
root@srv:~/dlm# php DLMTester.php -s "halt" ./INFO
PHP Parse error:  syntax error, unexpected '' {' (T_CONSTANT_ENCAPSED_STRING), expecting '{' in /root/dlm/search.php on line 4
root@srv:~/dlm# php DLMTester.php -s "halt" ./INFO
PHP Parse error:  syntax error, unexpected '' {' (T_CONSTANT_ENCAPSED_STRING), expecting '{' in /root/dlm/search.php on line 4
root@srv:~/dlm# php DLMTester.php -s "halt" ./INFO
PHP Parse error:  syntax error, unexpected '' {' (T_CONSTANT_ENCAPSED_STRING), expecting '{' in /root/dlm/search.php on line 4
`

I attached also the search.php and INFO created by the wizard, please can you help me? Thanks!
[files.zip](https://github.com/SplitCriteria/dlm-helper/files/9801958/files.zip)

**Comment by SplitCriteria** [comment]
It looks like you entered a couple apostrophes in the DLMHelper script which can cause errors when creating the class 'search.php' file.

I corrected your search.php and INFO files. However, you'll need to manually parse the results using a custom regular expression. Once you determine the regex to use, put that in line 39 of search.php. Then you'll need to enter the location of each of the search items (e.g. title, url) in lines 57-65 in search.php.
[corrections.zip](https://github.com/SplitCriteria/dlm-helper/files/10048179/corrections.zip)

**Comment by cipo80** [comment]
Hi, very thank you for the reply.
I'm trying to parse the search result to determine the regex, but I'm a "newbie", do you have some tips or procedure to do that?

Thanks!

**Comment by SplitCriteria** [comment]
I would recommend going to a regex "helper" website [like RegExr](https://regexr.com) where you can paste in the html of a sample results from the torrent website. That is, go to the torrent website and search for a file. Then copy the source html (usually right click and click "View Page Source") and paste it into the "text" section of a regex website. Next, you'll have to learn the basics of regular expressions (i.e. regex's) to create a regex which searches the page source to find those parameters that the Synology DLM expects (e.g. title, size, date).
