### ISSUE TITLE
Add support for accounts (private trackers)

### ISSUE THREAD

**Issue by Mavyre** [SplitCriteria/dlm-helper#3]
It'd be great to add support for private trackers protected with username/password.
Looks like the INFO must contain those two lines:
```json
"minfirmware": "2257",
"accountsupport": true,
```
and search.php must contain `public function VerifyAccount($username, $password)`

**Comment by SplitCriteria** [comment]
I haven't seen the new documentation for private trackers in Download Station. Do you know where the documentation is for private tracker support? If it's just those couple lines, then it should be very easy to add the capability.

**Comment by Mavyre** [comment]
I haven't seen up to date documentation for synology (yet). Seems like they added it discreetly. However, I've seen some examples on Syno Boost (http://www.synoboost.com/) and identified rapidly what was needed to make it work.

**Comment by SplitCriteria** [comment]
Thanks for the link -- I'll take a look at it
